# Description:
#    Helpful inspiration to draw something all pulled from Phil McAndrew's Big List of Stuff to Draw 
#
#    Sources: http://philintheblanks.com/thelist.html
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   hubot what are we drawing
#
# Author:
#   @gaufre

ideas = [
  "books (and people reading them)"
  "trophies (champion of _______!)"
  "statues (who deserves to to be immortalized as a statue?)"
  "dogs"
  "naked people"
  "all of houses you've lived in"
  "sad people"
  "bicycles"
  "your neighbors"
  "mounted animal heads"
  "a map of the world (try it from memory!)"
  "bugs"
  "people covered with tattoos"
  "fancy jewelry"
  "super wrinkly old people"
  "cats"
  "big spooky old houses"
  "Guy Fieri eating things he isn't supposed to eat (rocks, his sunglasses, toothpaste, etc)"
  "pizza (with unusual toppings?)"
  "people at the beach"
  "trees"
  "tree forts"
  "forest people"
  "newspapers (and people reading them)"
  "monsters"
  "people on skateboards (and falling off of them)"
  "people playing drums"
  "slugs"
  "sandwiches"
  "skulls"
  "bottles (full of beverages or potions or poison or water)"
  "fancy cakes"
  "tombstones or coffins"
  "cool shoes"
  "a map of your city or town"
  "computers (or devices with lots of buttons and wires)"
  "different kinds of chimneys (and people climbing out of them)"
  "crying children (why are they crying?)"
  "motorcycles"
  "witches"
  "animals with antlers"
  "people playing poker (what does a good poker face look like? what does a desperate gambler look like?)"
  "every teacher you've ever had (from memory)"
  "snakes (did they eat something interesting recently?)"
  "chairs and tables"
  "cacti"
  "hotdogs"
  "different kinds of hats"
  "people falling out of boats"
  "ghosts"
  "swords"
  "people in the middle of dental procedures"
  "horses"
  "people singing badly"
  "wizards"
  "umbrellas"
  "fictional sons of Mitt Romney (Chad Romney, Wipp Romney, Burp Romney, etc)"
  "coins"
  "stupid hair styles"
  "self portraits (what will you look at the age of 100?)"
  "vegetables"
  "flags for fictional countries"
  "birds doing stuff that birds aren't supposed to do"
  "pencils"
  "sweaty, out of breath joggers"
  "your worst fears"
  "people lifting weights"
  "sea shells"
  "house plants"
  "people playing basketball"
  "turkeys"
  "tentacles coming out of containers, bags, windows, etc"
  "airplanes"
  "fancy crowns"
  "fictional members of your family"
  "dinosaurs"
  "people 'doing science' (test tubes! strange chemicals! microscopes!)"
  "musical instruments"
  "castles"
  "teenagers"
  "snooty butlers carrying things on trays (telephones, food, unopened envelopes, small people)"
  "animals wearing glasses"
  "a volcanic island"
  "people with ice cream cones"
  "candles"
  "people standing behind one of those cartoony x-ray screens"
  "things that lives in caves and holes"
  "cardboard boxes"
  "your worst enemy"
  "a painter standing at an easel, painting something from life (nude model? landscape?)"
  "babies holding guns"
  "suits of armor"
  "fictional candy bars"
  "spaceships"
  "labels for fictional beers"
  "astronauts"
  "ears"
  "people with tons of facial piercings"
  "the moon"
  "forks and knives and spoons"
  "people with briefcases hoping no one knows what's inside the briefcase"
  "the aftermath of a car accident"
  "a snowman"
  "playing cards"
  "an idiot playing piano"
  "aliens"
  "microscopic organisms"
  "people skiing"
  "snails"
  "demons"
  "a fictional game show host"
  "sushi"
  "sewer people"
  "government spy drones"
  "a sentient brick wall"
  "coffee mugs"
  "a bow and arrow shoot-out"
  "a ferris wheel"
  "a fish tank"
  "booby traps"
  "swamp creatures"
  "Jay Leno weeping quietly while looking at his reflection in a mirror"
  "people slipping on banana peels"
  "balloons"
  "people with crutches or limbs in casts"
  "boogers"
  "pole-vaulters"
  "people stranded on desert islands"
  "a dog in handcuffs, surrounded by police"
  "turtles"
  "mountains"
  "things popping out of toasters (bread, pizza, books, etc)"
  "skeletons"
  "flowers"
  "people trapped in the belly of a whale"
  "Frankenstein's monster"
  "a terrarium"
  "people smooching"
  "people knitting scarves"
  "grumpy bartenders"
  "tents in the woods"
  "arctic explorers"
  "bridges"
  "a television set (what's on tv?)"
  "people working in gardens"
  "people stepping on bee hives"
  "a toothbrush"
  "PEZ dispensers"
  "tourists"
  "your childhood bedroom"
  "people digging holes"
  "a stamp collector and their stamps"
  "a person being eaten alive by feral dogs"
  "people wrapped in blankets"
  "bookshelves"
  "whatever you had for breakfast"
  "comfy armchairs"
  "abandoned buildings"
  "icebergs"
  "discarded underwear"
  "carnivorous furniture"
  "ducks"
  "hermits and their hermit houses"
  "hamburgers"
  "lizard men"
  "campfires"
  "people smoking pipes"
  "cliffs by the ocean"
  "people waiting in line to use the bathroom"
  "animals in hiding after escaping from a zoo"
  "dogs trying to reach food on tables"
  "garbage cans"
  "slime creatures"
  "crabs"
  "fictional members of the Wu-Tang Clan"
  "different types of helmets"
  "logs"
  "ceiling fans"
  "Rush Limbaugh's stupid face"
  "palm trees"
  "proud looking guys with flannel shirts and tool belts and hard hats and no pants"
  "dentures"
  "skeleton keys"
  "binoculars"
  "giant objects crashing into earth (giant baby, giant motorcycle, giant anvil, etc)"
  "exercise machines that could be mistaken for torture devices"
  "things hatching out of eggs (birds, lizards, guys in business suits, etc)"
  "animal skin rugs"
  "people blindly trying to find their missing glasses"
  "hockey players"
  "people flying around with jetpacks"
  "squirrels trying to drag things up into trees (an entire pizza, a piano, an old man, etc)"
  "proud idiot gun owners posing with guns"
  "vehicles that are shapes like food (hotdog car, banana car, pretzel car, etc)"
  "clocks"
  "chain link fences"
  "donuts"
  "people wearing ridiculous puffy shirts"
  "dartboard with darts in it (or around it)"
  "people being thrown or falling through glass windows"
  "members of fictional boy bands"
  "puddles"
  "people who are melting for some reason"
  "famous people's butts"
  "dirt"
  "plumbers tinkering with complicated pipe systems"
  "smelly cheeses"
  "cyclops"
  "spooky caves"
  "pieces in a chess set"
  "weird looking babies"
  "people trying to hold in farts while on dates"
  "fashionable dog collars"
  "moss"
  "ruins of castles, ancient temples, etc"
  "unusual body piercings"
  "cereal boxes"
  "unfortunate tattoos"
  "stand-up comedians"
  "robots"
  "people frozen in of giant hunks of ice"
  "fossils"
  "bones"
  "people modeling really complicated outfits"
  "old people trying to make sense of technology that they don't understand"
  "Harrison Ford"
  "zombies"
  "things on shelves (bottles, tools, etc)"
  "piñatas"
  "morons yelling at each other on fox news"
  "the biggest ice cream sundae ever"
  "a person kissing a framed photograph of Carl Sagan"
  "really big telescopes"
  "someone who hasn't yet realized thier clothing is on fire"
  "people painting graffiti"
  "cowboys"
  "surfers"
  "people wearing ugly wigs"
  "trains"
  "cookies"
  "pyramids"
  "people puking"
  "sharks"
  "too many people in one hot tub"
  "bombs"
  "teeth"
  "Guy Fieri lost in the wilderness"
  "people climbing ladders"
  "sumo wrestlers"
  "the people who write all those awful comments on youtube"
  "cave people"
  "a chef preparing a big meal"
  "cannibals"
  "shields (with cool designs, symbols, etc)"
  "birds flying around, carrying things in their talons (small animals, children, a gun, etc)"
  "politicians sitting in jail cells"
  "doctors trying to remove something from a terrified person's nose, nurses holding the person down"
  "a person with live snakes in their pockets"
  "people standing on logs, floating across bodies of water"
  "people with really complicated braces on their teeth"
  "a tornado"
  "dumptrucks"
  "farmers planting things, harvesting crops"
  "a blender (draw it before, during and after blending stuff!)"
  "aliens hiding in craters"
  "talk show hosts interviewing inanimate objects"
  "a high speed car chase (or horse chase, rollerblade chase, helicopter chase, etc)"
  "bank robbers"
  "crystals"
  "noodles"
  "rollercoasters"
  "pretzels"
  "buildings in your neighborhood (from memory or from life!)"
  "a person sitting at a desk, shouting into a phone (what are they shouting about?)"
  "swordfish"
  "bears"
  "hideous sweaters"
  "sunken ships at the bottom of the sea"
  "spiders"
  "unflattering portraits of bigots"
  "the toothfairy"
  "alligators"
  "people posing with fish they caught"
  "firefighters rescuing people from burning buildings"
  "broken mirrors"
  "Puff Daddy admiring a photograph of himself"
  "werewolves"
  "race car drivers"
  "people playing twister"
  "wet dogs"
  "lightning"
  "clouds"
  "bats (the animal)"
  "scuba divers"
  "rocks"
  "tree stumps"
  "toilets"
  "rats"
  "rain"
  "vacuum cleaners"
  "godzilla"
  "vampires"
  "animals wearing really expensive people clothes"
  "gondoliers"
  "playground stuff (slides, swings, monkeybars, etc)"
  "people falling off of trampolines"
  "shopping carts (full of groceries?)"
  "cars"
  "the president shaking hands with an alien"
  "people racing bobsleds"
  "clowns"
  "dog owners picking up dog poop"
  "people eating mud"
  "video game controllers"
  "pinball machines"
  "a bucket full of worms"
  "people playing ping-pong"
  "people wearing clothes that are either way too big or way too small"
  "frightened naked people being chased by animals"
  "people dancing"
  "giant floating eyeballs with telepathic powers"
  "a parade"
  "a shady looking man trying to sell lizards out of a suitcase"
  "mushrooms"
  "people using jumpropes"
  "mount rushmore (add new faces!)"
  "boats"
  "a blacksmith (what are they working on?)"
  "a photographer taking pictures (what are they photographing? animals? supermodels? food?)"
  "people sleeping in hammocks"
  "people falling out of hammocks"
  "people playing with hula hoops"
  "the statue of liberty"
  "a bunch of police cars crashing into each other"
  "a funeral"
  "people setting off or watching fireworks"
  "mermaids"
  "snow monsters"
  "camels"
  "UFOs abducting things (people, cows, trees, cars, etc)"
  "a person trying to chop down a tree"
  "feet"
  "tacos"
  "dogs peeing on things they're not supposed to pee on"
  "people hiding in trees or bushes"
  "a gang of women throwing a scantily clad man into a volcano"
  "people in a bowling alley"
  "skunks"
  "the night sky"
  "people taking showers"
  "police officers beating up innocent people while bank robbers excape"
  "boxers knocking each other out"
  "people in sleeping bags"
  "feathers"
  "mad scientists"
  "a map of your home (can you do it from memory?)"
  "a black hole (are spaceships are being sucked into it?)"
  "album covers for fictional bands"
  "people hiding in dumpsters"
  "boobs"
  "weeners"
  "spooky shadow figures"
  "futuristic versions of mundane things (coffee mug, chair, toothbrush, etc)"
  "handcuffs"
  "the sun"
  "maps of fictional states (South Kansas, West Vermont, Texas, etc)"
  "people exploring dark places with flashlights"
  "beetles"
  "ninjas"
  "people in bathtubs"
  "giraffes"
  "bigfoot"
  "greek gods"
  "people playing soccer"
  "opera singers"
  "footsteps in snow"
  "waterfalls"
  "your hands"
  "people eating in a fancy restaurant"
  "scissors"
  "things being launched with catapults (rocks, cows, Rush Limbaugh, etc)"
  "evil cult members performing secret dark rituals"
  "a bull totally wrecking a matador"
  "people playing golf (what sort of stupid outfits are they wearing?)"
  "jazz musicians"
  "people wearing capes"
  "elves"
  "cabins in the woods (or on mountains or near lakes or on the moon)"
  "people who have lots of secrets"
  "blanket forts"
  "whales"
  "fog"
  "people singing karaoke"
  "people being injected with syringes"
  "your desk and everything on it"
  "people getting smooshed by giant fingers"
  "grasshoppers"
  "people doing yoga (make up ridiculous new poses!)"
  "ballerinas"
  "rhinos"
]

module.exports = (robot) ->
  robot.hear /what are we drawing/i, (msg) ->
    msg.send msg.random ideas