# Description:
#    These are jokes
#
#    Sources: http://thoughtcatalog.com/christopher-hudspeth/2013/09/50-terrible-quick-jokes-thatll-get-you-a-laugh-on-demand/
#    http://www.funniestcleanjokes.com
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   hubot tell me a joke
#
# Author:
#   @gaufre

jokes = [
  "It’s hard to explain puns to kleptomaniacs because they always take things literally."
  "I used to think the brain was the most important organ. Then I thought, look what’s telling me that."
  "The midget fortune teller who kills his customers is a small medium at large."
  "A farmer in the field with his cows counted 196 of them, but when he rounded them up he had 200."
  "What does a nosey pepper do? Get jalapeño business."
  "The dyslexic devil worshipper sold his soul to Santa."
  "You kill vegetarian vampires with a steak to the heart."
  "There was a prison break and I saw a midget climb up the fence. As he jumped down her sneered at me and I thought, well that’s a little condescending."
  "A magician was walking down the street and turned into a grocery store."
  "Did you hear about the Mexican train killer? He had locomotives."
  "How does NASA organize their company parties? They planet."
  "Why can’t you hear a pterodactyl go to the bathroom? Because the “P” is silent."
  "What kind of shoes do ninjas wear? Sneakers."
  "Why does Snoop Dogg carry an umbrella? Fo’ drizzle."
  "Did you hear about the new corduroy pillows? They’re making headlines everywhere!"
  "Why was six afraid of seven? Because seven was a well known six offender."
  "What time is it when you have to go to the dentist? Tooth-hurtie."
  "My friend recently got crushed by a pile of books, but he’s only got his shelf to blame."
  "What did Jay-Z call his girlfriend before they got married? Feyoncé."
  "Time flies like an arrow, fruit flies like banana."
  "What do you call dangerous precipitation? A rain of terror."
  "What’s the best part about living in Switzerland? Not sure, but the flag is a big plus."
  "Two fish are in a tank. One turns to the other and asks “How do you drive this thing?”"
  "Why can’t a bike stand on its own? It’s two tired."
  "Why didn’t the lifeguard save the hippie? Because he was too far out man!"
  "What do you call a big pile of kittens? A meowntain."
  "I wondered why the baseball was getting bigger. Then it hit me."
  "Atheism is a non-prophet organization."
  "Just went to an emotional wedding. Even the cake was in tiers."
  "When you get a bladder infection, urine trouble."
  "I wrote a song about a tortilla. Well actually, it’s more of a wrap."
  "What do you call a dinosaur with a extensive vocabulary? A thesaurus."
  "Marketing companies should use chromosomes in advertisements because sex cells."
  "Pampered cows produce spoiled milk."
  "Learn sign language, it’s very handy."
  "I started a band called 999 Megabytes — we haven’t gotten a gig yet."
  "What is the difference between ignorance and apathy? I don’t know, and I don’t care."
  "Dry erase boards are remarkable."
  "How do you make Holy water? Boil the hell out of it."
  "Having erroneously reported that the publisher of a rival local newspaper had died, we were forced to write a retraction that read, “we regret that the notice of Mr. Davis’s death was in error…”"
  "Outside the train station a kid selling newspapers bellowed, “Extra! Extra! Read all about it! Five men swindled!” A man walks up and buys the paper. After reading it he comes back to the kid. “Hey kid, I don’t see anything here about five people being swindled!” “Extra! Extra!” yells the boy. “Six men swindled!”"
  "I used to have a fear of hurdles. I got over it."
  "Why did the skeleton go alone to the movie? She had no BODY to go with."
  "I was wondering why the frisbee was getting bigger. Then it hit me."
  "Do not argue with an idiot. He will drag you down to his level and beat you with experience."
	"I want to die peacefully in my sleep, like my grandfather — not screaming and yelling like the passengers in his car."
	"I asked God for a bike, but I know God doesn't work that way. So I stole a bike and asked for forgiveness."
	"The last thing I want to do is hurt you. But it's still on the list."
	"Light travels faster than sound. This is why some people appear bright until you hear them speak."
	"If I agreed with you we'd both be wrong."
	"We never really grow up, we only learn how to act in public."
	"War does not determine who is right — only who is left."
	"Knowledge is knowing a tomato is a fruit; wisdom is not putting it in a fruit salad."
	"Evening news is where they begin with 'Good evening', and then proceed to tell you why it isn't."
	"If God is watching us, the least we can do is be entertaining."
	"If you think nobody cares if you're alive, try missing a couple of payments."
	"How is it one careless match can start a forest fire, but it takes a whole box to start a campfire?"
	"A bus station is where a bus stops. A train station is where a train stops. On my desk, I have a work station.."
	"Did you know that dolphins are so smart that within a few weeks of captivity, they can train people to stand on the very edge of the pool and throw them fish?"
	"I thought I wanted a career, turns out I just wanted paychecks."
	"A computer once beat me at chess, but it was no match for me at kick boxing."
	"I didn't say it was your fault, I said I was blaming you."
	"The shinbone is a device for finding furniture in a dark room."
	"Why does someone believe you when you say there are four billion stars, but check when you say the paint is wet?"
	"You do not need a parachute to skydive. You only need a parachute to skydive twice."
	"A clear conscience is usually the sign of a bad memory."
	"Laugh at your problems, everybody else does."
	"It's not the fall that kills you; it's the sudden stop at the end."
	"Artificial intelligence is no match for natural stupidity."
	"Always borrow money from a pessimist. He won't expect it back."
	"He who smiles in a crisis has found someone to blame."
	"I intend to live forever. So far, so good."
	"Worrying works! 90% of the things I worry about never happen."
	"I like work. It fascinates me. I sit and look at it for hours."
	"I always take life with a grain of salt. A grain of salt, a slice of lemon, and a shot of tequila."
	"Never hit a man with glasses. Hit him with a baseball bat."
	"There's a fine line between cuddling and holding someone down so they can't get away."
	"I used to be indecisive. Now I'm not sure."
	"When tempted to fight fire with fire, remember that the Fire Department usually uses water."
	"You are such a good friend that if we were on a sinking ship together and there was only one life jacket... I'd miss you" "heaps and think of you often."
	"Knowledge is power, and power corrupts. So study hard and be evil."
	"With sufficient thrust, pigs fly just fine."
	"A TV can insult your intelligence, but nothing rubs it in like a computer."
	"If winning isn't everything, why do they keep score?"
	"Whoever coined the phrase \"Quiet as a mouse\" has never stepped on one."
	"Nostalgia isn't what it used to be."
	"Why do ducks have webbed feet? To stamp out fires. Why do elephants have flat feet? To stamp out burning ducks."
		"Why was the robot angry? ...because someone kept pushing his buttons!"
	"What's a robots favorite type of music?... Heavy Metal!"
	"What do you get when you cross a robot and a tractor?... A Trans-Farmer! Get it? GET IT?!"
	"I can't believe I was once fired from the calendar factory.  All I did was take a day off."
	"I'd tell you a chemistry joke, but I know I wouldn't get a reaction."
	"My first job was working in an orange juice factor, but I got canned: couldn't concentrate."
	"I want to make a joke about sodium... But Na.."
	"I hate insect puns, they really bug me."
	"Why did the bee get married? ...because he found his honey."
	"What do sea monsters eat for lunch? Fish and ships."
	"I got caught stealing a calender once. I got 12 months."
	"Never trust atoms. They make up everything."
	"If Apple made car, would it have Windows?"
	"How does Moses make his tea?  Hebrews it."
	"A ham sandwich walks into a bar and orders a beer. The Bartender says, "Sorry, we don't serve food here.""
	"How do you make holy water?  You boil the hell out of it."
	"Two guys walk into a bar, the third one ducks."
	"I had a dream I was a muffler last night. I woke up exhausted!"
	"What is Beethoven’s favorite fruit? A Ba-na-na-na."
	"Did you know that 5/4 people admit they’re bad with fractions?"
]

module.exports = (robot) ->
  robot.hear /tell me a joke/i, (msg) ->
    msg.send msg.random jokes
